### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by geom16011** [samapriya/Clip-Ship-Planet-CLI#9]
Trying to install it in windows and i get the following error 

Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    long_description=open('README.rst').read(),
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\encodings\cp1253.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9c in position 10550: character maps to <undefined>

Any ideas?

**Comment by samapriya** [comment]
This project has been retired and will no longer be updated.
